name: Source Code Lint and Fix

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - '**.cs'
      - '**.yml'
  pull_request:
    branches: [ main ]
    paths:
      - '**.cs'
      - '**.yml'

jobs:
  run-linters:
    name: Source code linters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Lint C#
        uses: wearerequired/lint-action@v2
        with:
          commit_message: "style(code): code style issues with ${linter}"
          dotnet_format: true
          dotnet_format_dir: src
          dotnet_format_auto_fix: true
          auto_fix: true
          git_name: "C# linter"

      - name: Lint yaml
        uses: ibiqlik/action-yamllint@v3